### ISSUE TITLE
Transfer views and urls from 'Classnote' app to 'accounts' app

### ISSUE THREAD

**Issue by parthpandyappp** [parthpandyappp/Classroom#14]
We want to transfer all the views and URL mappings related to accounts present in classnote app to accounts app where actually they should be. Only views to be transferred and not the templates, the templates should have the same path as they have at present.

**Comment by IgnisDa** [comment]
Cool I will do it. Please assign me this issue.

**Comment by parthpandyappp** [comment]
Sure! You're great to go!
Issue assigned to @IgnisDa

**Comment by parthpandyappp** [comment]
Issue fixed by @IgnisDa
