### ISSUE TITLE
Stop user from being joining a same class again and again.

### ISSUE THREAD

**Issue by parthpandyappp** [parthpandyappp/Classroom#18]
At present, we have implemented so many functionalities with proper DBMS set-up for our ease, but one thing is to be done is that we don't want a user to join the same class again and again. If user has not already joined that particular class then user can join that class normally, but if user has already joined that class, he should be given a message on the screen that "You've already joined the class".

**Comment by arunsri7** [comment]
Can I take this up?

**Comment by IgnisDa** [comment]
I can help with this! Please assign it to me if you can.

**Comment by parthpandyappp** [comment]
@arunsri7 You can also work on this issue.
You can too create  a Pull Request on this issue.
No worries! Happy Hacking!

**Comment by parthpandyappp** [comment]
Issue fixed by @IgnisDa 
PR #19 fixes it
